[build]
  base = "/opt/build/repo/shop"  # Path to the base directory of the project
  command = "npm run build"  # Command to run for building the site
  publish = "/opt/build/repo/shop/build"  # Path to the build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
