[build]
  base = "/opt/build/repo/shop"  # Corrected path without the extra /opt/build/repo/
  command = "npm run build"
  publish = "/opt/build/repo/shop/build"  # Ensure this matches the build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
