[build]
  base = "/opt/build/repo/shop"
  command = "npm run build"
  publish = "/opt/build/repo/shop/build"  # Adjust to 'shop/build'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
