[build]
  base = "shop"             # Path to the directory containing your source code
  command = "npm run build"  # Command to build your project
  publish = "shop/build"     # Output directory to deploy

[[redirects]]
  from = "/*"               # Redirect all traffic
  to = "/index.html"        # Send it to index.html
  status = 200              # Status code for successful redirect
